name: lint-py

on:
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/lint-py.yml"
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/lint-py.yml"

jobs:
  lint-py:
    name: lint (python)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - name: Install pylint
        run: pip3 install pylint

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter for images code
        run: find . -name "*.py" ! -path "*/tests/*" | xargs pylint

      - name: Install pylint dependencies for tests
        run: pip3 install pytest

      - name: Run linter for tests code
        run: find "./tests" -name "*.py" | xargs pylint --rcfile=pylintrc.tests
